# Generated by Django 5.1 on 2024-09-02 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoName', models.CharField(max_length=50)),
                ('todoDescription', models.TextField()),
                ('isDone', models.BooleanField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 9, 2, 12, 18, 12, 522194, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
